"""Built-in brand kit presets for subtitle styling."""

PRESETS = {
    "viral_yellow": {
        "font_size": 68,
        "primary_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "outline_color": "#000000",
        "outline_width": 3,
        "position": "center",
        "max_words_per_line": 5,
        "animation": "word_highlight",
        "background_color": None,
        "background_padding": 12,
    },
    "neon_blue": {
        "font_size": 64,
        "primary_color": "#FFFFFF",
        "highlight_color": "#00D4FF",
        "outline_color": "#000033",
        "outline_width": 3,
        "position": "center",
        "max_words_per_line": 5,
        "animation": "word_highlight",
        "background_color": None,
        "background_padding": 12,
    },
    "fire_red": {
        "font_size": 66,
        "primary_color": "#FFFFFF",
        "highlight_color": "#FF3333",
        "outline_color": "#1A0000",
        "outline_width": 3,
        "position": "center",
        "max_words_per_line": 5,
        "animation": "word_highlight",
        "background_color": None,
        "background_padding": 12,
    },
    "minimal_white": {
        "font_size": 58,
        "primary_color": "#FFFFFF",
        "highlight_color": "#FFFFFF",
        "outline_color": "#333333",
        "outline_width": 3,
        "position": "center",
        "max_words_per_line": 5,
        "animation": "none",
        "background_color": "#00000099",
        "background_padding": 16,
    },
    "gradient_purple": {
        "font_size": 64,
        "primary_color": "#E0AAFF",
        "highlight_color": "#C77DFF",
        "outline_color": "#240046",
        "outline_width": 3,
        "position": "center",
        "max_words_per_line": 5,
        "animation": "fade_in",
        "background_color": None,
        "background_padding": 12,
    },
}
